name: Dataset validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - jumli_*/**
      - mapmysite/**
      - Cargo.lock
      - Cargo.toml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: true
          shared-key: "ci"
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Run validator
        run: cargo run --bin jumli_validator -- jumli_data/records
